apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-service-account
  namespace: default

  annotations:
    # This annotation links K8s Service Account
    # to Azure Managed Identity!
    # Client ID comes from terraform output:
    # managed_identity_client_id
    azure.workload.identity/client-id: "__MANAGED_IDENTITY_CLIENT_ID__"

  labels:
    # This label enables Workload Identity
    # for this service account
    azure.workload.identity/use: "true"